#!/usr/bin/with-contenv sh
                                                                                                                 
exec s6-setuidgid jenkins /usr/local/bin/plugins.sh /tmp/files/plugins.txt